//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryStatus
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> TimeOrder { get; set; }
        public string IdOrder { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
