//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationItem
    {
        public int Id { get; set; }
        public Nullable<int> IdLoc { get; set; }
        public Nullable<int> IdItem { get; set; }
        public Nullable<decimal> Xaxis { get; set; }
        public Nullable<decimal> Yaxis { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Location Location { get; set; }
    }
}
