//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchebka.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality
    {
        public int Id { get; set; }
        public string IdOrder { get; set; }
        public string Examination { get; set; }
        public Nullable<int> IdParametr { get; set; }
        public string Comment { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual QualityParametr QualityParametr { get; set; }
    }
}
